name: Crypto ETL Pipeline

on:
  schedule:
    - cron: '0 2 * * *'   
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    env:
      coin_geko_api_key: ${{ secrets.COIN_GEKO_API_KEY }}
      n8n_web_hook: ${{ secrets.N8N_WEB_HOOK }}
      alpha_vintage_api_key: ${{ secrets.ALPHA_VINTAGE_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pandas python-dotenv

      - name: Create raw_protfolio.csv from Secret
        env:
          PORTFOLIO_DATA: ${{ secrets.CLIENT_PORTFOLIO_CSV }}
        run: echo "$PORTFOLIO_DATA" > raw_protfolio.csv

      - name: Run ETL script
        run: python main_code.py
